-- Separate customer-signed AOD from EFEX-emailed AOD
-- signed_aod_url = customer digital signature PDF (generated by system)
-- aod_pdf_url    = EFEX-sent AOD from email (unchanged, auto-populated by email poller)
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS signed_aod_url TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS signed_aod_at TIMESTAMPTZ;
